### ISSUE TITLE
Account errors on Devnet.

### ISSUE THREAD

**Issue by graxler** [orao-network/solana-vrf#1]
The program works fine on local host but as soon as I switch to Devnet the tests fail.

I’ve spent hours looking through the code to find a solution but my only guess is that it’s something to do with the before block in the tests file.

Have you got any ideas on how to fix this?

**Comment by graxler** [comment]
I still can’t get it to connect to devnet or testnet. Keep getting Transaction Simulation Failed 0x0 Error.

If anyone has any ideas why please let me know!

**Comment by orao-dev1** [comment]
Hi @graxler.

If you're trying to run CPI tests on devnet it will surely fail as VRF tests can't be setup inside the "before" block. All tests are setup for the local environment.
In case you really want to do it like that then be sure to remove the "before" block and remove all fulfillEmulation calls as well (since VRF already exists and working on devnet/mainnet). Some additional changes might be required.

In case you want to try the CPI example in action, [try the roulette-cli as suggested.](https://github.com/orao-network/solana-vrf/tree/master/rust/examples/cpi#how-to-play)

**Comment by graxler** [comment]
Thank you so much for your response! 

I’ve removed the before block and fulfil emulation, now it’s giving me “Error number 6009: Unknown Treasury”

I’m using the roulette CPI example you provided, I’ve literally copy and pasted the code and removed unnecessary code but still can’t get it working😔

**Comment by orao-dev1** [comment]
Random treasury is generated for the Test VRF, but for Devnet VRF the actual treasury must be used, i.e. the one stored in its on-chain configuration.

**Comment by graxler** [comment]
How would I use the actually treasury, could you provide an example please? I just can’t figure it out.

**Comment by orao-dev1** [comment]
Here's how to get the actual configuration: https://github.com/orao-network/solana-vrf/blob/master/js/tests/index.ts#L42
And here's how to put the actual treasury into the list of instruction accounts: https://github.com/orao-network/solana-vrf/blob/master/js/tests/index.ts#L48

**Comment by graxler** [comment]
I can finally get it connected to Devnet (Thank you!), but now It's producing zero randomness again.. how would I resolve this?

**Comment by orao-dev1** [comment]
The randomness will be fulfilled by configured VRF authorities as soon as possible, but not immediately due to commitment requirements and asynchronous nature of the solana blockchain. I.e. you should wait a few blocks for randomness to be fulfilled. Here's how the [VRF example app](https://github.com/orao-network/solana-vrf/blob/72c9db9f686d3dc991426c8f7af0dc37874fb0e7/rust/examples/off-chain/src/main.rs#L42) does it.

**Comment by orao-dev1** [comment]
@graxler I assume it's OK to close this issue now?

**Comment by anilaravindv** [comment]
Hi,
Randomness is not yet fullfilled..
how do i fullfill the randomness? Here is my code : 
-------------------------------------------------------

    const seed1 = web3.Keypair.fromSeed(Buffer.alloc(32));
    
    const [seed, tx2] = await (await vrf.request(seed1.publicKey.toBytes())).rpc();
    const randomness = await vrf.getRandomness(force.toBuffer());
    //await delay(3000);
    const rnd = randomness.fulfilled();
    if (rnd == null) {
      console.log("Randomness is not yet fulfilled...");
    } else {
      console.log(
        "Randomness is fulfilled with the new " + randomness.randomness
      );
    }

**Comment by anilaravindv** [comment]
Oh sure , so basically I should keep waiting in a loop untill randomness.fulfilled is turned true?

**Comment by orao-dev1** [comment]
yes

**Comment by orao-dev1** [comment]
We've just updated the package and introduce waitFulfilled(seed). Be sure to pull the latest changes.

**Comment by anilaravindv** [comment]
Ok. thanks
